### ISSUE TITLE
PR UI usability improvements

### ISSUE THREAD

**Issue by dbuenzli** [moby/datakit#493]
Don't know how it's exactly called. But I'm talking about this UI:

https://ci.ocaml.io/ocaml/opam-repository/pr/8625

1. It's quite inconvenient to use on small screens. The window split should be resizable.
2. Please report failures *first* on the page. I'm not interested in crawling through green checkmarks to try to spot the red failures.
3. Making the log lines addressable for referencing would be nice.

**Comment by talex5** [comment]
Note: @samoht removed the split screen UI in #501, so that shouldn't be a problem now.
