### ISSUE TITLE
build failure: mtime.os not found

### ISSUE THREAD

**Issue by avsm** [moby/datakit#554]
```
+ jbuilder "build" "-p" "datakit-bridge-github" "-j" "2" (CWD=/home/opam/.opam/4.03.0/build/datakit-bridge-github.0.10.1)
- Error: Findlib package "mtime.os" not found.
```
https://ci.ocaml.io/log/saved/docker-build-b37536fba3c79e97d3d40292c260d777/868edc49a8ad3ede93298e8b206a564e273ee30b

It might be due to https://github.com/ocaml/opam-repository/pull/9121

**Comment by samoht** [comment]
Should be fixed in opam-repo by https://github.com/ocaml/opam-repository/pull/9152/commits/31b3d4e21ac857e96fab3c66526830f92e1c368f

**Comment by samoht** [comment]
Move to mtime 1.0 is done in #560
