### ISSUE TITLE
Package `datakit_io' not found - required by `datakit'

### ISSUE THREAD

**Issue by nickbetteridge** [moby/datakit#580]
I'm trying to compile ```datakit/src/datakit/bin/main.ml``` and with all of the opam installed packages - datakit, datakit-client, datakit-server (0.10.1) - I get ```ocamlfind: Package `datakit_io' not found - required by `datakit'```.
I've tried building datakit_io as a separate package and installing it, but this is ignored and the same error reappears.
ocaml 4.04, opam 1.2.2
Any suggestions or work-arounds?

**Comment by nickbetteridge** [comment]
Cut and pasted locally in the end - must learn Docker :)

**Comment by avsm** [comment]
glad its fixed, just ping here if you run into any more issues!

**Comment by samoht** [comment]
I am getting the same issue, I guess nobody tried to used `datakit` as an external library before ... I will fix this.
