### ISSUE TITLE
Invalid use of `${ROOT}`

### ISSUE THREAD

**Issue by diml** [moby/datakit#597]
While analyzing packages using jbuilder I found a few use of `${ROOT}` in datakit to point to the root of the project. This doesn't work in general, as the expansion of `${ROOT}` depends on the workspace configuration. This means that you can't build datakit when it is a subdirectory in a bigger workspace.

To help with this, I added `${SCOPE_ROOT}` in the development version, which always point to the first parent directory containing `<package>.opam` files (see [here](http://jbuilder.readthedocs.io/en/latest/project-layout-specification.html#scopes) for more details).

**Comment by talex5** [comment]
(looks like this isn't in 1.0+beta10, so we'll need to wait for the next release)

**Comment by samoht** [comment]
Fixed by hardcoding the path instead of using `SCOPE_ROOT`, but fixed anyway.
