### ISSUE TITLE
Minor release with s/per_file/per_module/ ?

### ISSUE THREAD

**Issue by diml** [moby/datakit#608]
I'm planning to remove support for `per_file` in jbuilder soon so that we can make progress on https://github.com/janestreet/jbuilder/pull/111. According to [this](https://github.com/janestreet/jbuilder-universe), datakit is the last package in opam that uses `per_file`. Could we have a minor release just changing `per_file` to `per_module`?

**Comment by talex5** [comment]
Looks like @samoht fixed this in https://github.com/moby/datakit/commit/f9ef3c97e9c6a49edc27c497aa89beafd674efa7#diff-83dee8443b77e780b8f9acfe6f8084e1.

@samoht: is there anything left to do before making another release?

**Comment by samoht** [comment]
Various dependencies of datakit (including ocaml-git, irmin, github-hook, session) are still stuck at using older conduit/cohttp versions. I think I managed to update everything (apart I saw some weirdness with latest conduit+launchd that I need to investigate) and I created https://github.com/moby/datakit/pull/609 to reflect these changes.

**Comment by samoht** [comment]
This is done with the 0.12 release
