### ISSUE TITLE
DataKitCI: configure docker run

### ISSUE THREAD

**Issue by Thegaram** [moby/datakit#623]
I am trying to create a local git workflow based on the self-ci example. I want my CI to build a docker container and then run it.

These are my tests (the rest of the file is mostly identical to self-ci):
```ocaml
[
  "build",  check_builds images#my_app;
  "run",    images#my_app >>= fun image ->
  (Docker.run 
     (Docker.command ~logs ~pool ~timeout:(30. *. minute) ~label:"test_run" [])
     image)
  >|= fun () -> "Run succeeded"
]
```

However, for my setup, I'd use the following command when running manually:

```
$ docker build -t my_app .
$ docker run --network host my_app
```

Is it possible to pass arguments like `--network host` to DataKitCI's Docker utilities?

**Comment by talex5** [comment]
What is the use for this? I worry that testing two PRs at the same time with a fixed network might cause a port conflict.

**Comment by Thegaram** [comment]
Well DataKitCI aims to be a generic CI solution right? I would like to use it for my CI scenario, where I have two containers, one with the service I am testing and the other one with my acceptance tests. For the latter to be able to access the service, I need to use Docker run's `--network` parameter.

It would also be nice to specify other parameters for Docker run, including port mappings. I've seen [mirageCI](https://github.com/avsm/mirage-ci/blob/master/src/docker_run.ml)'s Docker utility has some more configuration options (e.g. volumes, tags), but I would prefer not to reimplement a utility like this when DataKitCI has it already.

Yeah I can see that if the CI runs the tests for PRs parallelly, then this can cause problems if the container exposes any ports (which is not the case for my tests). What do you suggest? Would it be possible to parameterize Docker.run's separately for PRs?

**Comment by talex5** [comment]
How do the acceptance tests access the service, if it doesn't expose any ports? Is there a fixed test container, or a new one for each PR?

**Comment by Thegaram** [comment]
Sorry I was not clear enough. The service container does expose ports, but for now, it is not started by the CI. The test container is built and run for each commit/PR.

More generally, I think it would be nice if DataKitCI could support more complex build/test scenarios involving multiple containers communicating with each other.

**Comment by talex5** [comment]
Yes. It probably needs docker-compose support, really.
