### ISSUE TITLE
Assert_failure ci/src/cI_monitored_pool.ml:44:2

### ISSUE THREAD

**Issue by Thegaram** [moby/datakit#628]
I am building a custom CI pipeline based on `self-ci`. Sometimes I get the following errors:

```
ci_1  | 2018-03-23 10:37.45 INF [datakit-ci] Record: status-myproject-ref-heads-master: build_and_run_tests -> "Assert_failure ci/src/cI_monitored_pool.ml:44:2"
ci_1  | 2018-03-23 10:37.45 INF [datakit-ci] Record: status-myproject-ref-heads-master: build_container -> "Assert_failure ci/src/cI_monitored_pool.ml:44:2"
```

It seems like DataKitCI is in an inconsistent state (see [this](https://github.com/moby/datakit/blob/master/ci/src/cI_monitored_pool.ml#L44) line). Maybe it is because I stopped the containers (`datakit/ci`, `datakit/db`, and `datakit/local-bridge`) using `docker kill`.

Right now the only way to get out of this situation is to rebuild my CI code, restarting the CI server is not enough. Is there a better way? Maybe flush the monitored pool somehow?

**Comment by talex5** [comment]
This means you're trying to create two resource pools with the same name. Since pools should only be created at startup, and this is being reported as a test result, you're probably trying to create a new pool for each test.

The pools are memory-only, so restarting will clear the state.

Make sure that your `my_tests` function doesn't create any pools (and doesn't call any function that takes a `~logs` argument - it's possible that one of them creates a pool internaly).

**Comment by Thegaram** [comment]
Oh okay, I accidentally still had some new pools apparently. Looking out for `~logs` helped, thanks!

**Comment by Thegaram** [comment]
I was wrong, it still doesn't work. I have the following code (which, in many ways, is analogous to the one in `self-ci`):

```ocaml
module Tests = struct
  open Term.Infix

  let repos =
    object(_self)
      method main_repo = Git.v ~logs ~remote:"/mnt/myproject_remote" "/data/repos/myproject"
    end

  let images src =
    let timeout = (30. *. minute) in
    let tests_dockerfile = Docker.create ~logs ~pool ~timeout ~label:"tests_docker" "Dockerfile" in
    object(_self)
      method tests = src >>= Docker.build ?from:None tests_dockerfile
    end

  let commands =
    let timeout = (30. *. minute) in
    object(_self)
      method run_tests = Docker.command ~logs ~pool ~timeout ~label:"tests" ~network:"host" []
    end

  let check_run term =
    term >|= fun _ -> "Run succeeded"

  let tests target =
    let src = Git.fetch_head repos#main_repo target in
    let images = images src in

    [
      "build_and_run_tests", check_run (images#tests >>= Docker.run commands#run_tests);
    ]

end

let projects = [
  Config.project ~id:"me/myproject" (Tests.tests)
]
```

At first it runs fine, but if I restart the CI I get `"Assert_failure ci/src/cI_monitored_pool.ml:44:2"`. I might be missing some trivial point, I am fairly new to OCaml.

**Comment by talex5** [comment]
`commands#run_tests` is a method call. It will create a new cache every time you run it. You probably want something like:

```ocaml
  module Commands = struct
    let timeout = 30. *. minute
    let run_tests = Docker.command ~logs ~pool ~timeout ~label:"tests" ~network:"host" []
  end
```

**Comment by Thegaram** [comment]
Worked, thanks!
