### ISSUE TITLE
CI: local state repo

### ISSUE THREAD

**Issue by Thegaram** [moby/datakit#630]
If I want to see the state history in DataKitCI, I need to configure `~state_repo` for `Web.config`, i.e. store the state history in a separate GitHub repo. Is it possible to store the state history in a local git repo instead?

I've tried specifying a local `~state_repo`, adding an empty git repository as a volume through docker-compose, but when I try to check the status history, I get `Not Found`.

**Comment by talex5** [comment]
The state is already stored in the local DataKit repository. However, to view it in a browser you need a web interface to it. `state_repo` is the URL of the web interface. Currently, it probably only works with GitHub.

(you need to be a bit careful when syncing to GitHub, as they may get annoyed if you push too much data)

You can also navigate the history using DataKitCI's own web UI (e.g. the `Previous state` link), although it may not be as easy to use. The hash it displays is the Git hash, so you can also use that with the regular Git tools (e.g. `git log`, `gitk`, etc).

**Comment by Thegaram** [comment]
I see. So if the state is already stored locally, I guess it would be possible to navigate the history (`history`, `head history`, `status history for this head`) without GitHub. I might look into this in the future.
