### ISSUE TITLE
Datakit-CI is rebuilding PR on title edit

### ISSUE THREAD

**Issue by kit-ty-kate** [moby/datakit#632]
Using the datakit's github-bridge and datakit-ci when a PR title is being edited the PR in question will get a signal to get rebuilt.
Is there a way to avoid that ?

**Comment by talex5** [comment]
It will get a signal that something has changed. It won't actually rebuild, unless the title of the PR is part of a cache key (which seems unlikely).

**Comment by kit-ty-kate** [comment]
mmh that might be related to something else indeed (*). Do you have any pointer/documentation on how the cache works ?

(*): the master branch has changed and we use a hash of the dockerfile used for the build pretty much everywhere in the cache but I'm wondering why changes in the master branch didn't trigger a build then. Is the signal done per branch/PR ?

**Comment by talex5** [comment]
Any time there is any change to the metadata, we recalculate all the terms (for all branches and PRs). We rely on the caches to avoid unnecessary rebuilds.

The cache is documented here: https://github.com/moby/datakit/blob/master/ci/src/datakit_ci.mli#L568
